services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: wedding-planner-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db
      - garage

  reverb:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: wedding-planner-reverb
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
    ports:
      - "${REVERB_SERVER_PORT:-8090}:${REVERB_SERVER_PORT:-8090}"
    command: php artisan reverb:start

  node:
    build:
      context: ./resources
      dockerfile: ../.docker/node/Dockerfile
    container_name: wedding-planner-node
    working_dir: /app
    volumes:
      - ./resources:/app
      - node_modules_data:/app/node_modules
      - ./.env:/app/.env
    ports:
      - "${VITE_PORT:-5173}:5173"
    environment:
      - NODE_ENV=development

  garage:
    build:
      context: .docker/garage
    container_name: wedding-planner-garage
    environment:
      GARAGE_BUCKET: ${AWS_BUCKET}
      GARAGE_KEY_ID: ${AWS_ACCESS_KEY_ID}
      GARAGE_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3900:3900"
    volumes:
      - garage_meta_data:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  db:
    image: postgres:16
    container_name: wedding-planner-db
    command: postgres -p ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  vendor_data:
  node_modules_data:
  garage_meta_data:
  garage_data:
