services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wending-planner-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/public/build
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: wending-planner-db
    command: postgres -p ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
