/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    DrawerToogle: typeof import('./src/components/DrawerToogle.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LayoutPanel: typeof import('./src/components/LayoutPanel.vue')['default']
    MenuToogle: typeof import('./src/components/MenuToogle.vue')['default']
    RadialMeter: typeof import('./src/components/RadialMeter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SimulationSwitcher: typeof import('./src/components/SimulationSwitcher.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
